config/routes.rb
V3::Application.routes.draw do

  match "admin/:model" => "admin#index" , :as=>"admin_index"
  match '/auth/:provider/callback' => "authentications#create"
  devise_for :users, :controllers => {:registrations => 'registrations' }

  resources :authentications
  resources :restaurants do
    get :find, :on=>:collection
    resources :reviews, :except=>[:index]
    resources :courses, :except=>[:index]
  end
  resources :photos
  resource :courses,:only=>[:index,:new,:create,:edit]
  resources :reviews, :only => [:index]
  resources :users #, :except =>[:edit]
  resources :ticketlines, :only =>[:index, :new]

  root :to => "application#main"

end

app/models/ticketline.rb
# coding: UTF-8
class Ticketline < ActiveRecord::Base
  belongs_to :review
  belongs_to :course

  def self.filter_fields
    [:course_name_contains,:review_title_contains]
  end

  def self.table_fields
    [:id, :review_title, :course_name, :quantity]
  end
  def review_title
    "#{review_id}(#{review.title})"
  end
  def course_name
    course.name
  end
end

app/controllers/ticketlines_controller.rb
class TicketlinesController < ApplicationController
  before_filter :find_ticketline,  :only => [:show, :edit, :update, :destroy]

  def show;  end

  def new
    @ticketline = Ticketline.new(:quantity=>1)
    @ticketline.course = Course.find(params[:course_id])
    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  def edit;  end

  def create
    @ticketline = Ticketline.new(params[:ticketline])
    @ticketline.save ? redirect_to(@ticketline, :notice => 'Linea creada') : render(:new)
  end

  def update
    @ticketline.update_attributes(params[:ticketline]) ? redirect_to(@ticketline, :notice => 'Linea actalizada.') : render(:edit)
  end

  def destroy
    @ticketline.destroy
    redirect_to(ticketlines_url)
  end

  private
  def find_ticketline
     @ticketline = Ticketline.find(params[:id])
  end

end

app/helpers/ticketlines_helper.rb
module TicketlinesHelper
end

app/views/ticketlines/_form.html.haml
- random = Time.now.usec
.ticketline.dot-underlined.full{'data-course'=>ticketline.course.id}
  = nested_hidden_field_for('review', ticketline, random, :id, ticketline.id) if ticketline.id
  .name= ticketline.course.name
  = nested_hidden_field_for('review', ticketline, random,:course_id,ticketline.course.id)
  .x.right-text x
  .quantity= nested_text_field_for('review', ticketline, random,:quantity,1)
  .price.right-text= ticketline.course.price.to_s
  .coin-symbol.right-text €

app/views/ticketlines/_ticketline.html.haml
.ticketline.full.dot-underlined
  .name= ticketline.course.name.humanize
  .x.right-text x
  .quantity.center-text= ticketline.quantity.to_s
  .price.right-text= ticketline.course.price.to_s
  .coin-symbol.right-text €

app/views/ticketlines/edit.html.haml
%h1= t '.title'
%p
  = link_to t('back'), ticketlines_path
  = link_to t('show'), @ticketline
= render 'form'

app/views/ticketlines/index.html.haml
%h1= t('.title')
%p= link_to t('.new_ticketline'), new_ticketline_path

%table
  %thead
    %tr
      %th= Ticketline.human_attribute_name :review_id
      %th= Ticketline.human_attribute_name :course_id
      %th= Ticketline.human_attribute_name :quantity
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for ticketline in @ticketlines
      %tr{ :class => cycle(:odd, :even) }
        %td= ticketline.review_id
        %td= ticketline.course_id
        %td= ticketline.quantity
        %td.action= link_to t('show'), ticketline
        %td.action= link_to t('edit'), edit_ticketline_path(ticketline)
        %td.action= link_to t('destroy'), ticketline, :confirm => t('are_you_sure'), :method => :delete

app/views/ticketlines/index.js.erb
$("nav.col a").attr("data-active",false).filter("[resource=ticketlines]").attr("data-active",true);
displaceHighlight();
$("section.col .index").fadeOut(200,function(){
    $(this).html( $("<%= escape_javascript( render "shared/index_partials/index" ) %>") ).fadeIn(200);
});

app/views/ticketlines/new.html.haml
%h1= t '.title'
%p= link_to t('back'), ticketlines_path
= render 'form'

app/views/ticketlines/new.js.erb
var $added = $("<%= escape_javascript(render 'form',:ticketline=>@ticketline )%>");
$added.addClass('highlighted');
$("#ticket .lines").append( $added );
sumTicket();

app/views/ticketlines/search.js.erb
// Recarga la tabla de resultados con los satisfacieron la busqueda
<%= escape_javascript(render "shared/js_partials/refresh_list_and_pagination") %>

app/views/ticketlines/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), ticketlines_path
  = link_to t('edit'), edit_ticketline_path(@ticketline)

%dl
  %dt= Ticketline.human_attribute_name :review_id
  %dd= @ticketline.review_id
  %dt= Ticketline.human_attribute_name :course_id
  %dd= @ticketline.course_id
  %dt= Ticketline.human_attribute_name :quantity
  %dd= @ticketline.quantity