config/routes.rb
V3::Application.routes.draw do

  match "admin/:model" => "admin#index" , :as=>"admin_index"
  match '/auth/:provider/callback' => "authentications#create"
  devise_for :users, :controllers => {:registrations => 'registrations' }

  resources :authentications
  resources :restaurants do
    get :find, :on=>:collection
    resources :reviews, :except=>[:index]
    resources :courses, :except=>[:index]
  end
  resources :photos
  resource :courses,:only=>[:index,:new,:create,:edit]
  resources :reviews, :only => [:index]
  resources :users #, :except =>[:edit]
  resources :ticketlines, :only =>[:index, :new]

  root :to => "application#main"

end

app/views/shared/common/_appropiate_input.html.haml
- default = params[:search].try(:[],field) || params[:user].try(:[],field) || form.object.try(field)
- type = klass.columns_hash[field.to_s].type unless defined?(type)
- x = case type
- when :string  then form.text_field(field, :value => default)
- when :password  then form.password_field field
- when :integer then COLLECTIONS.keys.include?(field) ? form.collection_select(field, COLLECTIONS[field].sort {|a,b| a[0] <=> b[0]},:first,:last, {:selected => default},{ :class=>'select_form white'}) : form.text_field(field, :value => default)
- when :date then form.date_select field, {:order =>[:day,:month,:year], :start_year=>1940, :end_year=>Time.now.year ,:value => default},{:class=>'select_form white select_'+field.to_s}
- when :text then form.text_area field, :value => default
- when :boolean then form.check_box field, :value=>default
- when :float then form.text_field field, :value=>default
- else klass.columns_hash[field.to_s].type
= x

app/views/shared/common/_appropiate_input_tag.html.haml
- x = case @model_class.columns_hash[field.to_s].type
- when :string  then field==:email ? email_field_tag(field) : text_field_tag(field)
- when :integer then COLLECTIONS.keys.include?(field) ? select_tag(field, options_for_select( (COLLECTIONS[field].collect {|c| [c.last , c.first] })).sort {|a,b| a[1] <=> b[1]} ) : text_field_tag(field)
- when :text then text_area_tag field
- when :date then date_select field, :order =>[:day,:month,:year]
- when :boolean then check_box_tag field
- when :float then text_field_tag field
- else @model_class.columns_hash[field.to_s].type
= x

app/views/shared/common/_courses_fieldset.html.haml
%fieldset.standard_fieldset{:id=>"courses_fieldset"}
  %h3.legend= t(:courses).humanize
  %h6.superindex.right-text Cuanta más información del menú, mejor. El precio no puede estar en blanco.
  -if action_name=='edit'
    = render 'courses/menu',:restaurant=>@restaurant
  -else
    .restaurant_menu
      %ul.menu-nav
        - FOOD_CATEGORIES.each do |index, cat|
          %li.cat-link{'data-cat'=>index}=cat
      .menu
        .category_wrapper
          - FOOD_CATEGORIES.each_with_index do |obj,cat_index|
            .category{'data-cat'=>cat_index, :class=>((cat_index==0 ? 'center' : 'right')+(cat_index==1 ? ' first' : ''))}
              %h1= obj[1].to_s
              - @restaurant.courses.each_with_index do |c, course_index|
                =render(c) if c.category==cat_index
              .add_course_link= link_to " + Añadir plato", new_courses_path(:category=>cat_index), :remote=>true

app/views/shared/common/_customized_pagination.html.haml
%nav.paginate
  - current_page, total_pages = models.current_page, models.total_pages
  - start_page, end_page = [current_page - 2,1].max, [current_page + 2, total_pages ].min
  .pagination
    .pages
      - if models.current_page > 1
        = link_to "<<", { :page => 1, :search=>params[:search] }, :rel => :first, :remote=>true
        = link_to "<", { :page => current_page - 1, :search=>params[:search] }, :rel => :previous, :remote=>true
      - else
        %em <<
        %em <
      - if show_range
        - for i in start_page..current_page-1 do
          = link_to i.to_s, { :page => i , :search=>params[:search]}, :remote => true
        %em= current_page
        - for i in current_page + 1..end_page do
          = link_to i.to_s,{ :page => i, :search=>params[:search] }, :remote => true
      - if models.current_page < models.total_pages
        = link_to ">", { :page => current_page + 1, :search=>params[:search] }, :rel => :next, :remote=>true
        = link_to ">>", { :page => total_pages , :search=>params[:search] }, :rel => :last, :remote=>true
      - else
        %em >
        %em >>
    .x_of_x
      %span= "#{current_page} de #{total_pages}"

app/views/shared/common/_field.html.haml
- error = form.object.errors[field[0]]
.field{:class=> (error.size>0 ? ' has_errors' : '') }
  .label.right-text
    = form.label field, t(field[0]).humanize
    - error.each do |e|
      .explanation.error_explanation= e.humanize
  .input{:class=>('date' if field[1]==:date)}
    = render "shared/common/appropiate_input",:form=>form, :field=>field[0], :type=>field[1]

app/views/shared/common/_fieldset.html.haml
- map = defined?(has_map) ? has_map : false; locate = defined?(geolocate) ? geolocate : false
%fieldset{:id=>"#{legend}_fieldset", :class=> ('map_fieldset' if map) }
  - if legend
    %h3.legend= label_tag t(legend).humanize
    %h6.right-text.superindex= explanation if defined?(explanation)
  -if map
    .edit_map_buttons.float-left{:style=>'width: auto;'}
      #capture_sv.center-text.round-corners=image_tag "camera_white_mini.png",:alt=>"Guardar coordenadas de StreetView"
      #put_marker.center-text.round-corners=image_tag "google-marker-white-mini.png",:alt=>"Colorcar marcador"
    #photo_effect.medium_map
    #map_canvas.medium_map.edit_map
  - fields.each do |field|
    = render 'shared/common/field',:form=>form,:field=>field
  - if locate
    #geolocate.fake_button
      =image_tag "iconos/google-marker-gray-min.png"
      .text Localizar

app/views/shared/common/_fieldset_bicolumn.html.haml
%fieldset.bicolumn{:id=>"#{legend}_fieldset"}
  %h3.legend=label_tag t(legend).humanize
  %h6.right-text.superindex= explanation if defined?(explanation)
  .half.left
    -puts "WOOOOO = "+fields.select {|f| fields.index(f) % 2 == 0 }.inspect
    - fields.select {|f| fields.index(f) % 2 == 0 }.each do |field|
      = render 'shared/common/field',:form=>form,:field=>field
  .half.right
    -puts "WEEEE = "+fields.select {|f| fields.index(f) % 2 != 0 }.inspect
    - fields.select {|f| fields.index(f) % 2 != 0 }.each do |field|
      = render 'shared/common/field',:form=>form,:field=>field

app/views/shared/common/_fieldset_old.html.haml
%fieldset.standard_fieldset{:id=>"#{legend}_fieldset"}
  - if legend
    .legend=label_tag t(legend).humanize
    .explanation= explanation if defined?(explanation)
  -if defined?(has_map)
    #capture_sv=image_tag "camera_white_mini.png",:alt=>"Guardar coordenadas de StreetView"
    #put_marker=image_tag "google-marker-white-mini.png",:alt=>"Colorcar marcador"
    #photo_effect.medium_map
    #map_canvas.medium_map.edit_map
  -fields.each_with_index do |field,index|
    - error = form.object.errors[field]
    .field{:class=> (defined?(has_map)? "invisible" : '') + (error.size>0 ? ' has_errors' :'') }
      .col.label
        = form.label field, t(field).humanize
        - error.each do |e|
          .explanation.error_explanation= e.humanize
      .col.input{:class=>('date' if form.object[field].class==Date)}
        - if defined?(types)
          = render "shared/common/appropiate_input",:form=>form,:field=>field, :type=>types[index]
        - else
          = render "shared/common/appropiate_input",:form=>form,:field=>field, :klass=>klass
  -if defined?(geolocate)
    #geolocate.fake_button
      =image_tag "iconos/google-marker-gray-min.png"
      .text Localizar

app/views/shared/common/_percentage_bar.html.haml
.percentage_bar
  - if !name.nil?
    .name= name
  .value
    .indicator
      .bar{:style=>"width: #{val*width}px"}
      -if percent
        .percent.center-text= percent == true ? (val.round(2)*100).to_i.to_s + '%' : percent

app/views/shared/common/_photos_fieldset.html.haml
%fieldset#photos_fieldset
  %h3.legend= t(:photos).humanize
  - form.object.photos.each do |photo|
    = render photo,:editable=>true
  .add_photo_link=link_to "+ Añadir foto", new_photo_path(:attachable_id=>form.object.id, :attachable_type=>form.object.class.name), :remote=>true

app/views/shared/common/_show_stars.html.haml
- label = defined?(valoration) ? valoration : nil
.stars.show{:class=>(defined?(mini) && mini ? 'mini' : '' ) + (label ? '' : ' no-label' ) }
  - if label
    .label= label_tag t(label)
  .stars_list
    -  rating = puntuation
    - impar = rating%2
    - (rating/2).times do
      = image_tag 'iconos/star_mini.png'
    = image_tag 'iconos/star_mini_yellow_gray.png' if impar==1
    - (5 - (rating/2+impar)).times do
      =image_tag "iconos/star_mini_gray.png"

app/views/shared/common/_ticketlines_fieldset.html.haml
%fieldset{:id=>"#{legend}_fieldset"}
  %h3.legend ¿Qué has comido?
  %h6.right-text.superindex Haz doble click(beta) o arrastra platos hasta el ticket. Si no encuentras lo que pediste, añadelo.
  =render "courses/menu", :restaurant=>@review.restaurant, :review=>@review
  #ticket.ticket
    %h1 Ticket
    .lines
      - @review.ticketlines.each do |t|
        =render 'ticketlines/form',:ticketline=>t
    .total.full
      .name.right-text Total
      .price.right-text 0
      .coin-symbol.right-text €

app/views/shared/common/_upload_photo_field.html.haml
.field{'data-hidden'=>false}
  .upload_field
    - if f.object.image.exists?
      .photos
        .photo
          = image_tag( f.object.image.url(:medium))
          .delete_inner.remove_photo_link
    - else
      .delete_photo= image_tag "deleteIcon_12.png",:class=>:remove_photo_link
      .photo_upload
        .input=f.file_field(:image)
        = f.hidden_field :_destroy
      .selected_file