config/routes.rb
V3::Application.routes.draw do

  match "admin/:model" => "admin#index" , :as=>"admin_index"
  match '/auth/:provider/callback' => "authentications#create"
  devise_for :users, :controllers => {:registrations => 'registrations' }

  resources :authentications
  resources :restaurants do
    get :find, :on=>:collection
    resources :reviews, :except=>[:index]
    resources :courses, :except=>[:index]
  end
  resources :photos
  resource :courses,:only=>[:index,:new,:create,:edit]
  resources :reviews, :only => [:index]
  resources :users #, :except =>[:edit]
  resources :ticketlines, :only =>[:index, :new]

  root :to => "application#main"

end

app/controllers/courses_controller.rb
# coding: UTF-8
class CoursesController < ApplicationController
  respond_to :html, :js
  before_filter :find_course, :only => [:show, :edit, :update, :destroy]

  def show; end

  def new
    @course = Course.new(:category=>params[:category])
    @review = Review.find(params[:review_id]) if params[:review_id]
    respond_to do |format|
      format.html # new.html.erb
      format.js { params[:restaurant_id].nil? ? render("new_nested") : @course.restaurant = Restaurant.find(params[:restaurant_id]) }
    end
  end

  def edit
    @review = Review.find(params[:review_id]) if params[:review_id]
  end

  def create
    @course = Course.new(params[:course])
    @course.user = current_user
    @course.restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.find(params[:review_id]) if params[:review_id]
    render(:js=>"alert('El formulario contiene errores')") unless @course.save
  end

  def update
    @review = Review.find(params[:review_id]) if params[:review_id]
    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(@course, :notice => t(:updated_ok)) }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.js
    end
  end

  private

  def redirect_unless_admin
    redirect_to(root_path,:notice=>t(:admins_only)) unless current_user && current_user.admin
  end
  def find_course
    @course = Course.find(params[:id])
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.haml
.course.full.dot-underlined{'data-id'=>course.id, :draggable=>(defined?(draggable) ? draggable.to_s : 'true')}
  .name= course.name
  .price.right-text= course.price.to_s
  .coin-symbol.right-text €
  .edit.center-text=link_to "Editar", edit_restaurant_course_path(course.restaurant,course, :review_id=>(review.id if (defined?(review) && review )) ), :remote=>true
  .link= link_to '',new_ticketline_path(:course_id=>course.id), :remote=>true, :class=>:add_ticketline_link, 'data-course'=>course.id

app/views/courses/_course_nested.html.haml
-random = Time.now.usec
%li.course.full.dot-underlined{:class=>'removable'}
  .name= nested_text_field_for('restaurant',course,random,:name,'Nombre')
  .cat.hidden= nested_hidden_field_for('restaurant',course,random,:category)
  .price.right-text= nested_text_field_for('restaurant',course,random,:price,'Precio')
  .coin-symbol.right-text  €
  .edit.editing
    = image_tag 'iconos/diskette_save_black_mini.png',:class=>'save_course'
    = image_tag 'iconos/trash_black_mini.png', :class=>:delete_nested_course

app/views/courses/_form.html.haml
-random= Time.now.usec
%li.course.full.dot-underlined{'data-random'=>random}
  = form_for([restaurant,course], :remote=>true) do |f|
    .name= f.text_field :name, :placeholder=>'Nombre'
    .cat.hidden= f.hidden_field :category
    .price.right-text= f.text_field :price,:placeholder=>'Precio'
    .coin-symbol.right-text  €
    .edit.editing
      = hidden_field_tag :random,random
      = (hidden_field_tag :review_id, review.id) if defined?(review) && review
      = image_tag 'iconos/diskette_save_black_mini.png',:class=>'save_course'
      = link_to (image_tag('iconos/trash_black_mini.png')),[restaurant,course],:class=>:delete_course, :method=>:delete, :remote=>true

app/views/courses/create.js.erb
$(".course[data-random=<%= params[:random] %>]").replaceWith("<%= escape_javascript( render @course, :review=>(@review if defined?(@review)) ) %>");        

app/views/courses/destroy.js.erb
$("#edit_course_<%= params[:id] %>").closest('.course').remove();

app/views/courses/edit.js.erb
$(".course[data-id=<%=@course.id %>]").replaceWith("<%= escape_javascript( render 'form',:restaurant=>@course.restaurant,:course=>@course, :review=>(@review if defined?(@review)) ) %>");

app/views/courses/index.html.haml
.index
  = render "shared/index_partials/index"

app/views/courses/index.js.erb
$("nav.col a").attr("data-active",false).filter("[resource=courses]").attr("data-active",true);
displaceHighlight();
$("section.col .index").fadeOut(200,function(){
    $(this).html( $("<%= escape_javascript( render "shared/index_partials/index" ) %>") ).fadeIn(200);
});

app/views/courses/new.js.erb
var $form = $("<%= escape_javascript( render 'form',:restaurant=>@course.restaurant,:course=>@course, :review=>(@review if defined?(@review)) ) %>");
$form.hide();
$(".category[data-cat=<%= @course.category.to_s %>] .add_course_link").before($form);
$form.slideDown();

app/views/courses/new_nested.js.erb
$nested_course = $("<%= escape_javascript( render "course_nested",:course=>@course )%>");
$nested_course.hide();
$(".category[data-cat=<%= @course.category.to_s %>] .add_course_link").before($nested_course);
$nested_course.slideDown(400);

app/views/courses/search.js.erb
// Recarga la tabla de resultados con los satisfacieron la busqueda
<%= escape_javascript(render "shared/js_partials/refresh_list_and_pagination") %>

app/views/courses/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), courses_path
  = link_to t('edit'), edit_course_path(@course)

%dl
  %dt= Course.human_attribute_name :restaurant_id
  %dd= @course.restaurant_id
  %dt= Course.human_attribute_name :name
  %dd= @course.name
  %dt= Course.human_attribute_name :price
  %dd= @course.price
  %dt= Course.human_attribute_name :category
  %dd= @course.category

app/views/courses/update.js.erb
var $course = $("<%= escape_javascript( render @course, :review=>(@review if defined?(@review)) ) %>");
$(".course[data-random=<%= params[:random] %>]").replaceWith( $course );
var $tk = $(".ticketline[data-course=" + $course.data('id') + "]");
$tk.find(".name").html("<%= escape_javascript( @course.name.humanize ) %>");
$tk.find(".price").html("<%= escape_javascript( @course.price.to_s ) %> €");
sumTicket();