config/routes.rb
V3::Application.routes.draw do

  match "admin/:model" => "admin#index" , :as=>"admin_index"
  match '/auth/:provider/callback' => "authentications#create"
  devise_for :users, :controllers => {:registrations => 'registrations' }

  resources :authentications
  resources :restaurants do
    get :find, :on=>:collection
    resources :reviews, :except=>[:index]
    resources :courses, :except=>[:index]
  end
  resources :photos
  resource :courses,:only=>[:index,:new,:create,:edit]
  resources :reviews, :only => [:index]
  resources :users #, :except =>[:edit]
  resources :ticketlines, :only =>[:index, :new]

  root :to => "application#main"

end

app/controllers/reviews_controller.rb
# coding: UTF-8
class ReviewsController < ApplicationController
  before_filter :redirect_if_not_logged, :only => [:new, :edit, :update, :destroy]
  before_filter :find_review, :only => [:show, :edit, :update, :destroy]

  def show; end

  def new
    @review = Review.new
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    current_user.reviews.each { |r| redirect_to(edit_restaurant_review_path(r.restaurant, r), :notice=>'Ya tienes un opinion sobre este restaurante. Si quieres cambiar algo, edítala.') if (r.restaurant_id == @review.restaurant_id) }
    redirect_to(root_path, :notice=>"Se ha intentado hacer una review de un restaurante que no existe") unless @review.restaurant
  end

  def edit;  end

  def create
    # TODO: No puedo meter ticketlines desde nueva review, solo desde edit!! Error grave!! Arreglarlo!
    puts "Parametros del create = "+params.to_yaml
    photos = []
    params.each { |name, value| photos << value if name =~ /review_photos/ }
    @review = Review.new(params[:review])
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.user = current_user
    if @review.save
      photos.each do |id|
        @photo = Photo.find(id)
        @photo.attachable_id = @review.id
        @photo.save
      end
      redirect_to(@review.restaurant, :notice => t(:saved_ok))
    else
      backup = @review
      @review = Review.new(:restaurant_id=>backup.restaurant.id)
      backup.errors.each { |attr,msg| @review.errors.add attr, msg  }
      render :new
    end
  end

  def update
    @review.update_attributes(params[:review]) ? redirect_to(@review.restaurant, :notice => 'Opinión actualizada correctamente.') : render(:edit)
  end

  def destroy
    @review.destroy
    redirect_to(reviews_url)
  end

  private
  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html (MacBook-de-Miguel-Camba-Gamazo's conflicted copy 2010-12-17).haml
%article.review
  .col.author
    .avatar= image_tag(review.user.photos[0] ? review.user.photos[0].image.url(:thumbnail) : "no-avatar.png",:size => "113x113")
    %h4.username= review.user.username ? link_to(review.user.username, user_path(review.user) ) : "Anonymous"
    .stats
      .minilegend
        Stats
        .subindice= pluralize(review.user.reviews.count,"review")
      .stat Media: #{review.user.avg_rating}
      .stat Reputación: #{ review.user.reputacion }
      - best_rated = review.user.best_rated
      - if best_rated.count>0
        .stat
          Restaurantes Preferidos:
          - best_rated.each do |review|
            %p= link_to review.restaurant.name, review.restaurant
  .col.review_content
    .date
      - if review.user == current_user
        %span #{link_to("Editar Review", edit_restaurant_review_path(review.restaurant,review))} |#{link_to("Delete", restaurant_review_path(review.restaurant,review), :confirm => "Are you sure?", :method=>:delete)}
      = review.created_at.strftime("%d-%m-%y")
    %header
      .title= "\"#{review.title.capitalize}\""
      .subtitle= review.restaurant.name
    .text= review.opinion
    .opinion
      .recomendations
        .section_title Lo recomienda para ir:
        - review.recomended_for.each do |rec|
          %p=t(rec)
        .section_title No lo recomienda para ir:
        - review.unrecomended_for.each do |rec|
          %p=t(rec)
      .separator
      .valorations
        .section_title Valoraciones
        - review.ratings.each do |val|
          .valoration= render "/shared/common/show_stars",:review=>review,:valoration=>val
        .section_title Acudió
        %p= CUSTOMER_TYPES[review.customer_type]
    .extra_info
      .photos.photo_list
        .section_title Fotos
        - review.photos.each_with_index do |photo,i|
          %li.photo.small.very.scalable{ :class =>"photo#{i%3}"  }= image_tag_sized photo,:medium_cropped
      %div
      .menu
        .section_title Menu
        -#- review.courses.each do |course|
        -#  .course
        -#    .name= course.name.humanize
        -#    .price==#{course.price}€
        -#.total
        -#  .name Total
        -#  .price== #{(review.courses.map {|c| c.price}).sum}€

app/views/reviews/_review.html.haml
%article.review.full.dot-underlined
  .reviewer_info
    .photo= user_avatar(review.user,:thumbnail,'122x122')
    %h4.username= link_to review.user.nick, review.user
    %p.dot-underlined Estadísticas
    %h6.right-text.italic.superindex= pluralize(review.user.reviews.count, 'opinión', 'opiniones')
    = show_stars review.user.avg_rating, :average, :mini
    .full
      .half Reputación:
      .half.right-text= review.user.reputacion
    .full Rest preferidos
    .full
      - review.user.best_rated_restaurants.each do |rest|
        .ellipsis-text= link_to rest.name, rest
  .review_info
    %header.full
      .date.right-text
        - if current_user && ( review.user == current_user || current_user.admin? )
          #{link_to("Editar Opinión", edit_restaurant_review_path(review.restaurant,review))} | #{link_to("Borrar", [review.restaurant,review], :confirm => t(:are_you_sure), :method=>:delete)}
        = review.created_at.strftime("%d-%m-%y")
      .title "#{review.title.titleize}"
      .restaurant_name= review.restaurant.name.titleize
    .text.full= review.opinion.titleize
    .opinion.full
      .recomendations.half
        %h4 Lo recomienda para ir:
        - review.recommended_for.each do |rec|
          %p= label_tag(t(rec))
        %h4 No lo recomienda para ir:
        - review.unrecommended_for.each do |rec|
          %p= label_tag(t(rec))
      .stars_and_customer_type.half
        %h4 Valoraciones
        - review.ratings.each do |val|
          .full= show_stars review[val], val
        %h4 Acudió
        %p= label_tag(CUSTOMER_TYPES[review.customer_type])
    .extra_info.full.gray-with-gray-round-borders
      .half.photo_list
        %h3.center-text Fotos
        = render review.photos, :classes => 'small very scalable', :size => :medium_cropped
      .half.ticket
        %h3.center-text Menu
        .lines= render review.ticketlines
        .total.full
          .name.right-text Total
          .price.right-text #{(review.ticketlines.map {|t| t.course.price * t.quantity}).sum}
          .coin-symbol.right-text.float-right €

app/views/reviews/_tricolumn_form.html.haml
= form_for [@review.restaurant, @review],:html=>{:multipart=>true} do |f|
  .tricolumn
    %nav.col.gray_column.animated_menu= render "shared/common/nav_column",:sections=>[t(:opinion), t(:ratings), t(:recomendations), t(:about_your_visit), t(:courses) ]
    %section.col.middle
      %header#restaurant_header
        .restaurant_name= @review.restaurant.name
        .full
          .actions.half= link_to 'Volver al restaurante',@review.restaurant
          .restaurant_town.half= "#{@review.restaurant.town}(#{PROVINCES[@review.restaurant.province]})" unless @review.restaurant.town.blank?
      = render "shared/common/fieldset",:form=>f, :legend=>:opinion,:fields=>[[:title,:string],[:opinion,:text]]
      = render "shared/common/fieldset_bicolumn",:form=>f, :legend=>:ratings,:fields=>@review.ratings.map{|e| [e,:integer]}
      = render "shared/common/fieldset_bicolumn",:form=>f, :legend=>:recomendations,:fields=>@review.recomendations.map{|e| [e,:boolean]}
      = render "shared/common/fieldset",:form=>f, :legend=>:about_your_visit,:fields=>[:customer_type,:price,:main_food,:second_food].map{|e| [e,:integer]}
      = render "shared/common/ticketlines_fieldset",:form=>f,:legend=>:ticketlines
      .buttons.center-text
        .button=f.submit 'Crear '+t(f.object.class.name.downcase), :class=>:default_button
    %section.col
      = render "shared/common/photos_fieldset",:legend=>:photos,:form=>f,:attachable=>@review

app/views/reviews/edit.html.haml
-title "Editar review"
= form_for [@review.restaurant, @review],:html=>{:multipart=>true} do |f|
  = render_cell :tricolumn_form, :show, :form => f, :controller=>controller_name

app/views/reviews/index.html.haml
.index
  = render "shared/index_partials/index"

app/views/reviews/index.js.erb
$("nav.col a").attr("data-active",false).filter("[resource=reviews]").attr("data-active",true);
displaceHighlight();
$("section.col .index").fadeOut(200,function(){
    $(this).html( $("<%= escape_javascript( render "shared/index_partials/index" ) %>") ).fadeIn(200);
});

app/views/reviews/new.html.haml
- title "Nueva Opinión"
= form_for [@review.restaurant, @review],:html=>{:multipart=>true} do |f|
  = render_cell :tricolumn_form, :show, :form => f, :controller=>controller_name

app/views/reviews/new.js.erb
var p = {}, $fields_for, $fieldset, $added, $sender = $("#<%= params[:sender] %>"), key = "num_"+$sender.attr('rel');
p[key] = $.deparam.querystring($sender.attr("href"))[key];
if ( $sender.attr("id")=="add_photo_link" ){
    alert("photo_link");
    $fields_for = $("<%= escape_javascript( form_for(@review) { |f| render "shared/common/photos_fieldset",:form=>f,:legend=>:photos } )%>");
    $("#add_course_link").attr("href",$.param.querystring( $("#add_course_link").attr("href"), p ) );
    $added = $fields_for.find(".field:last").hide();
    $sender.parent().before($added);
    p[key] = parseInt( p[key] ) + 1;
    $sender.attr("href",$.param.querystring( $sender.attr("href"), p ) );
    $added.show(200);
} else if ( $sender.attr("id")=="add_course_link" ){
    var $new_course_field = $("<%= escape_javascript( render "courses/course_direct_form",:course=>Course.new(:category=>params[:category].to_i),:editable=>true ) %>");
    $(".category.visible .add_course_link").before( $new_course_field );
} else { alert("unknown sender"); }

app/views/reviews/search.js.erb
// Recarga la tabla de resultados con los satisfacieron la busqueda
<%= escape_javascript(render "shared/js_partials/refresh_list_and_pagination") %>

app/views/reviews/show.html.haml
- title "Show review"
.tricolumn
  %nav.col.gray_column= render "shared/restaurant_partials/left_col_show",:restaurant => @review.restaurant
  %section.col
    %header#restaurant_header
      .restaurant_name= @review.restaurant_name
      .full
        .actions.half= link_to("Editar opinión", edit_restaurant_review_path(@review.restaurant,@review)) if @review.user_id == current_user.try(:id)
        .restaurant_town.half= "#{@review.restaurant_town}(#{PROVINCES[@review.restaurant_province]})" if @review.restaurant_town.present?
    = render(@review)
  %section.col
    .legend= t(:photos).humanize
    = @review.restaurant.all_photos.size>=1 ? render("shared/common/popeye",:photos=>@review.restaurant.all_photos) : 'No hay fotos de este restaurante'